# Generated by Django 3.0.2 on 2020-02-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('synopsis', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('git', models.CharField(max_length=400)),
                ('language', models.CharField(choices=[('C', 'C'), ('CPP', 'C++'), ('HS', 'Haskell'), ('PL', 'Perl'), ('ELM', 'Elm'), ('JS', 'JavaScript'), ('TS', 'TypeScript'), ('JAV', 'Java'), ('C#', 'C#'), ('PUR', 'PureScript'), ('CL', 'Common Lisp'), ('SC', 'Scheme'), ('PY2', 'Python 2'), ('PY3', 'Python 3')], default=None, max_length=3)),
                ('framework', models.CharField(choices=[('NG', 'Angular'), ('NGJ', 'AngularJS'), ('EA', 'Elm Architecture'), ('PH', 'Phoenix'), ('DJ', 'Django'), ('DJR', 'Django Rest Framework')], default=None, max_length=3)),
            ],
        ),
    ]
