# Generated by Django 3.0.2 on 2020-02-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='project',
            name='framework',
            field=models.CharField(choices=[('NO', 'None'), ('NG', 'Angular'), ('NGJ', 'AngularJS'), ('EA', 'Elm Architecture'), ('PH', 'Phoenix'), ('DJ', 'Django'), ('DJR', 'Django Rest Framework'), ('EM', 'EmberJS')], default=None, max_length=3),
        ),
    ]
