# Generated by Django 3.0.2 on 2020-02-12 11:46

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='descriptions',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=250), size=None),
        ),
    ]
