# Generated by Django 3.0.2 on 2020-02-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_project_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='priority',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='example',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='framework',
            field=models.CharField(blank=True, choices=[('NO', 'None'), ('NG', 'Angular'), ('NGJ', 'AngularJS'), ('EA', 'Elm Architecture'), ('PH', 'Phoenix'), ('DJ', 'Django'), ('DJR', 'Django Rest Framework'), ('EM', 'EmberJS')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
