# Generated by Django 3.0.2 on 2020-02-17 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20200212_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='framework',
            field=models.CharField(blank=True, choices=[('NG', 'Angular'), ('NGJ', 'AngularJS'), ('EA', 'Elm Architecture'), ('PH', 'Phoenix'), ('DJ', 'Django'), ('DJR', 'Django Rest Framework'), ('EM', 'EmberJS'), ('LV', 'Laravel'), ('UN', 'Unity')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('C', 'C'), ('CPP', 'C++'), ('HS', 'Haskell'), ('PL', 'Perl'), ('ELM', 'Elm'), ('JS', 'JavaScript'), ('TS', 'TypeScript'), ('JAV', 'Java'), ('C#', 'C#'), ('PUR', 'PureScript'), ('CL', 'Common Lisp'), ('SC', 'Scheme'), ('PY2', 'Python 2'), ('PY3', 'Python 3'), ('PHP', 'PHP'), ('VAR', 'Various')], default=None, max_length=3),
        ),
    ]
