# Generated by Django 3.0.2 on 2020-02-17 08:43

from django.db import migrations, models
import django.utils.timezone
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20200217_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('authors', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=250), size=None)),
                ('journal', models.CharField(max_length=250)),
                ('publisher', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
