# Generated by Django 3.0.2 on 2020-02-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_publication_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='abstract',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
